baseurl = "https://www.joanpujol.cat"
title = "Joan Pujol"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
    author = "Joan Pujol"
    info = "Software Engineer"
    description = "Joan Pujol personal website"
    keywords = "developer,personal"
    avatarurl = "images/profile.png"

    favicon_32 = "/images/favicon-32x32.png"
    favicon_16 = "/images/favicon-16x16.png"

    footercontent = "God is in the detail / Devil is in the details <a href='https://en.wiktionary.org/wiki/devil_is_in_the_details#English' target='_blank'>( * )</a>" 

    hidecredits = false
    hidecopyright = false

    rtl = false

    math = true
    custom_css = ["css/custom.css"]

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/lujop/"
[[params.social]]
    name = "StackOverflow"
    icon = "fab fa-stack-overflow fa-2x"
    weight = 2
    url = "https://stackoverflow.com/users/269454/lujop"
[[params.social]]
    name = "Google Play"
    icon = "fab fa-google-play fa-2x"
    weight = 3
    url = "https://play.google.com/store/apps/developer?id=lujop&hl=en"    
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin fa-2x"
    weight = 3
    url = "https://www.linkedin.com/in/lujop/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 3
    url = "https://twitter.com/lujop"


[languages]
    [languages.en]
        languageName = "English"

    [languages.ca]
        languageName = "Català"
        info = "Enginyer Software"      
        footercontent = "Déu està en els detalls / El dimoni està en els detalls <a href='https://en.wiktionary.org/wiki/devil_is_in_the_details#English' target='_blank'>( * )</a>"         

    [languages.es]
        languageName = "Castellano"
        info = "Ingeniero Software" 
        footercontent = "Dios está en los detalles / El demonio está en los detalles <a href='https://en.wiktionary.org/wiki/devil_is_in_the_details#English' target='_blank'>( * )</a>"  


# Menu links
#[[menu.main]]
#    name = "Blog"
#    weight = 1
#    url  = "/posts/"
#[[menu.main]]
#    name = "About"
#    weight = 2
#    url = "/about/"